server:
  port: 8888
spring:
  application:
    name: Jhonathan-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhontahan/jhonathan-config-server.git
          default-label: main
          search-paths:
          - 'greeting-service*'
